using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using BattleCore;

namespace BattleCore.Tests
{
    /// <summary>
    /// Proves the C# port reproduces the TS core bit-for-bit. The fixture was
    /// generated by running the real TS implementation with Math.random() pinned
    /// to 0, so replaying the same action list under FixedRng(0) must yield the
    /// exact same BattleState at every step (all fields, card order, and log text).
    /// </summary>
    public class ParityTests
    {
        private static JsonElement LoadFixture()
        {
            string path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "parity-fixture.json");
            string json = File.ReadAllText(path);
            var doc = JsonDocument.Parse(json);
            return doc.RootElement.Clone();
        }

        private static BattleAction ParseAction(JsonElement action)
        {
            string type = action.GetProperty("type").GetString()!;
            return type switch
            {
                "PLAY_CARD" => new PlayCardAction(action.GetProperty("instanceId").GetString()!),
                "END_TURN" => new EndTurnAction(),
                "RESTART" => new RestartAction(),
                _ => throw new InvalidOperationException($"Unexpected action type '{type}'"),
            };
        }

        private static void AssertStateMatches(BattleState actual, JsonElement expected, int step)
        {
            string ctx = $"step {step}";

            Assert.That(actual.Turn, Is.EqualTo(expected.GetProperty("turn").GetInt32()), $"{ctx}: turn");
            Assert.That(actual.DistanceIndex, Is.EqualTo(expected.GetProperty("distanceIndex").GetInt32()), $"{ctx}: distanceIndex");
            Assert.That(actual.PlayerHp, Is.EqualTo(expected.GetProperty("playerHp").GetInt32()), $"{ctx}: playerHp");
            Assert.That(actual.PlayerStamina, Is.EqualTo(expected.GetProperty("playerStamina").GetInt32()), $"{ctx}: playerStamina");
            Assert.That(actual.PlayerGuard, Is.EqualTo(expected.GetProperty("playerGuard").GetInt32()), $"{ctx}: playerGuard");
            Assert.That(actual.EnemyHp, Is.EqualTo(expected.GetProperty("enemyHp").GetInt32()), $"{ctx}: enemyHp");
            Assert.That(actual.EnemyStamina, Is.EqualTo(expected.GetProperty("enemyStamina").GetInt32()), $"{ctx}: enemyStamina");
            Assert.That(actual.LogSeq, Is.EqualTo(expected.GetProperty("logSeq").GetInt32()), $"{ctx}: logSeq");
            Assert.That(actual.Result.ToToken(), Is.EqualTo(expected.GetProperty("result").GetString()), $"{ctx}: result");

            AssertPileMatches(actual.Hand, expected.GetProperty("hand"), step, "hand");
            AssertPileMatches(actual.DrawPile, expected.GetProperty("drawPile"), step, "drawPile");
            AssertPileMatches(actual.DiscardPile, expected.GetProperty("discardPile"), step, "discardPile");
            AssertLogMatches(actual.Log, expected.GetProperty("log"), step);
        }

        private static void AssertPileMatches(
            IReadOnlyList<PrototypeCard> actual, JsonElement expected, int step, string pile)
        {
            int expectedCount = expected.GetArrayLength();
            Assert.That(actual.Count, Is.EqualTo(expectedCount), $"step {step}: {pile} count");
            for (int i = 0; i < expectedCount; i++)
            {
                string expectedId = expected[i].GetProperty("instanceId").GetString()!;
                Assert.That(actual[i].InstanceId, Is.EqualTo(expectedId), $"step {step}: {pile}[{i}] instanceId");
                // defId string must round-trip to the exact TS token.
                Assert.That(actual[i].DefId.ToToken(), Is.EqualTo(expected[i].GetProperty("defId").GetString()),
                    $"step {step}: {pile}[{i}] defId");
            }
        }

        private static void AssertLogMatches(IReadOnlyList<LogEntry> actual, JsonElement expected, int step)
        {
            int expectedCount = expected.GetArrayLength();
            Assert.That(actual.Count, Is.EqualTo(expectedCount), $"step {step}: log count");
            for (int i = 0; i < expectedCount; i++)
            {
                Assert.That(actual[i].Id, Is.EqualTo(expected[i].GetProperty("id").GetInt32()), $"step {step}: log[{i}] id");
                Assert.That(actual[i].Text, Is.EqualTo(expected[i].GetProperty("text").GetString()), $"step {step}: log[{i}] text");
            }
        }

        [Test]
        public void FullTrace_MatchesTsGoldenFixture()
        {
            var fixture = LoadFixture();
            Assert.That(fixture.GetArrayLength(), Is.GreaterThan(1), "fixture must contain an INIT step plus actions");

            var rng = new FixedRng(0);

            // Step 0 is the INIT snapshot.
            var first = fixture[0];
            Assert.That(first.GetProperty("action").GetProperty("type").GetString(), Is.EqualTo("INIT"),
                "first fixture element must be INIT");

            var state = BattleReducer.InitState(rng);
            AssertStateMatches(state, first.GetProperty("state"), 0);

            for (int i = 1; i < fixture.GetArrayLength(); i++)
            {
                var element = fixture[i];
                var action = ParseAction(element.GetProperty("action"));
                state = BattleReducer.Reduce(state, action, rng);
                AssertStateMatches(state, element.GetProperty("state"), i);
            }
        }
    }
}
